#!/usr/bin/env python3
"""Build a static Zenodo-ready release copy of the visualization site."""

from __future__ import annotations

import json
import shutil
import zipfile
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
DIST = ROOT / "dist"
PACKAGE_DIR = ROOT / "zenodo-package"
MANIFEST = ROOT / "_site-manifest.json"

SITE_FILES = [
    "_site-manifest.json",
    "_site-nav.js",
    "_site-shared.css",
    "index.html",
    "module-emission-propagation.html",
    "module-interferometry-instrumentation.html",
    "README.md",
    "CITATION.cff",
    ".nojekyll",
    ".zenodo.json",
    "LICENSE",
    "RELEASE.md",
    "ZENODO_DEPOSIT.md",
    "emission-mechanism-explorer-narratives.qmd",
]

IGNORE_NAMES = {".DS_Store", "__pycache__"}


def require(condition: bool, message: str) -> None:
    if not condition:
        raise SystemExit(f"release build failed: {message}")


def copy_path(src: Path, dst: Path) -> None:
    if src.is_dir():
        if dst.exists():
            shutil.rmtree(dst)
        shutil.copytree(src, dst, ignore=shutil.ignore_patterns(*IGNORE_NAMES))
    elif src.exists():
        if src.name in IGNORE_NAMES:
            return
        dst.parent.mkdir(parents=True, exist_ok=True)
        shutil.copy2(src, dst)


def validate_release_inputs(manifest: dict) -> None:
    collection = manifest.get("collection") or {}
    pages = manifest.get("pages") or []

    require(collection.get("version"), "_site-manifest.json is missing collection.version")
    require(collection.get("date"), "_site-manifest.json is missing collection.date")
    require(pages, "_site-manifest.json does not list any pages")

    for page in pages:
        filename = page.get("filename")
        require(filename, "manifest page is missing filename")
        require((ROOT / filename).exists(), f"manifest page is missing from disk: {filename}")
        for dep in page.get("dependencies", []):
            require((ROOT / dep).exists(), f"dependency for {filename} is missing: {dep}")
        screenshot = page.get("screenshot")
        if screenshot:
            require((ROOT / screenshot).exists(), f"screenshot for {filename} is missing: {screenshot}")

    zenodo = json.loads((ROOT / ".zenodo.json").read_text())
    for field in ("title", "description", "creators", "license", "upload_type", "access_right"):
        require(zenodo.get(field), f".zenodo.json is missing {field}")

    expected_version = collection["version"].lstrip("v")
    require(
        zenodo.get("version") == expected_version,
        f".zenodo.json version must be {expected_version}",
    )
    require(
        zenodo.get("publication_date") == collection["date"],
        f".zenodo.json publication_date must be {collection['date']}",
    )


def write_manifest_js(manifest: dict) -> None:
    payload = json.dumps(manifest, indent=2)
    (DIST / "_site-manifest.js").write_text(f"window.PHYS681_SITE_MANIFEST = {payload};\n")


def write_deposit_contents(manifest: dict) -> None:
    lines = [
        "# Deposit Contents",
        "",
        "This file is generated by `tools/release/build_dist.py` for the Zenodo release package.",
        "",
        "## Entry Points",
        "",
        "- `index.html`: collection landing page",
        "- `module-emission-propagation.html`: emission and propagation module index",
        "- `module-interferometry-instrumentation.html`: radio interferometry and instrumentation module index",
        "- `emission-mechanism-explorer-narratives.html`: rendered narrative notes",
        "- `emission-mechanism-explorer-narratives.pdf`: PDF render of the narrative notes",
        "- `emission-mechanism-explorer-narratives.qmd`: Quarto source for the narrative notes",
        "",
        "## Included Interactive Pages",
        "",
    ]
    for page in manifest["pages"]:
        if page.get("status") == "defer":
            continue
        release_level = "Core" if page.get("tier") == "A" else "Supplemental"
        lines.append(f"- `{page['filename']}` — {page['title']} ({page['module']}, {release_level})")
    lines.extend([
        "",
        "## Metadata",
        "",
        "- `_site-manifest.json`: machine-readable page inventory and learning goals",
        "- `CITATION.cff`: citation metadata",
        "- `.zenodo.json`: Zenodo deposition metadata",
        "- `LICENSE`: licensing summary",
        "- `README.md`: local preview and publication notes",
        "",
        "## Excluded From This Deposit",
        "",
        "Development, backup, planning, cache, and generated QA folders are intentionally excluded.",
        "",
    ])
    (DIST / "DEPOSIT_CONTENTS.md").write_text("\n".join(lines))


def prune_ignored_files() -> None:
    for path in DIST.rglob("*"):
        if path.name in IGNORE_NAMES:
            if path.is_dir():
                shutil.rmtree(path)
            else:
                path.unlink()


def archive_name(manifest: dict) -> str:
    version = (manifest.get("collection") or {}).get("version", "v0.0.0")
    safe_version = version.replace("/", "-")
    return f"phys681-solar-physics-instruments-teaching-visualizations-{safe_version}.zip"


def make_zip(manifest: dict) -> Path:
    if PACKAGE_DIR.exists():
        shutil.rmtree(PACKAGE_DIR)
    PACKAGE_DIR.mkdir()
    archive_path = PACKAGE_DIR / archive_name(manifest)
    files = sorted(path for path in DIST.rglob("*") if path.is_file() and path.name not in IGNORE_NAMES)
    with zipfile.ZipFile(archive_path, "w", compression=zipfile.ZIP_DEFLATED) as archive:
        for path in files:
            archive.write(path, path.relative_to(DIST))
    return archive_path


def main() -> int:
    manifest = json.loads(MANIFEST.read_text())
    validate_release_inputs(manifest)
    if DIST.exists():
        shutil.rmtree(DIST)
    DIST.mkdir()

    for name in SITE_FILES:
        copy_path(ROOT / name, DIST / name)
    write_manifest_js(manifest)

    for page in manifest["pages"]:
        copy_path(ROOT / page["filename"], DIST / page["filename"])
        for dep in page.get("dependencies", []):
            copy_path(ROOT / dep, DIST / dep)
        screenshot = page.get("screenshot")
        if screenshot:
            copy_path(ROOT / screenshot, DIST / screenshot)

    copy_path(ROOT / "figures" / "explorer-screenshots", DIST / "figures" / "explorer-screenshots")
    write_deposit_contents(manifest)
    prune_ignored_files()
    archive_path = make_zip(manifest)
    print(f"Release candidate written to {DIST}")
    print(f"Zenodo archive written to {archive_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
